Deterministic IPNS keypairs
KeychainMDIP/multi-dimension-identity-protocol pull request #2
Opened 2022-04-06 09:16 UTC by imthe-1

2022-04-07 19:17 UTC, mandeeps708 requested changes

2022-04-07 19:17 UTC, mandeeps708 commented on lib/utils/util.js
> +    const plainText = await eccrypto.decrypt(Buffer.from(privateKey, 'hex'), payload);
Probably we can do Promise.all() on all the promises outside the loop?

https://eslint.org/docs/rules/no-await-in-loop

2022-04-07 19:17 UTC, mandeeps708 commented on test/integration/btc.did.test.js
> +  broadcast,
We can probably comment this variable too if it's not needed temporarily yet, instead of overriding rule.

Similar instances in other test files.

2022-05-31 14:30 UTC, imthe-1 commented on lib/node/http.js
> +const props = propertiesReader(path.join(`${__dirname}/../../bin/etc/local.conf`));
this line has been removed with the new updates

2022-05-31 14:33 UTC, imthe-1 commented on lib/client/mdip.js
> +            throw new Error('Invalid DID Doc. Schema validation failed.');
agreed @mandeeps708. will be adding a function call here and update this in the subsequent PR.

2022-05-31 14:36 UTC, imthe-1 commented on lib/client/mdip.js
> +        value: parseInt(sendAmt * 10 ** 8, 10),
10 raised to the power of 8 i.e., 100000000. this is to convert amount in BTC to Satoshis. moved to constants.

2022-05-31 14:53 UTC, imthe-1 commented on .eslintrc.js
>      'no-plusplus': 'off',
marking it for the subsequent PR.

2022-05-31 15:17 UTC, mandeeps708 commented
@imthe-1 Can you please post the link to ClickUp card so that we can track the changes for subsequent PRs.

2022-05-31 23:09 UTC, imthe-1 commented
sure @mandeeps708. here we go:
https://app.clickup.com/t/2ebkum4

2022-06-01 05:43 UTC, mandeeps708 approved these changes

2022-06-06 18:00 UTC, merged