Support for btc payment transactions
KeychainMDIP/multi-dimension-identity-protocol pull request #5
Opened 2023-11-24 18:56 UTC by macterra

2023-12-05 15:13 UTC, macterra commented on lib/client/mdip.js
> +        sequence: 0xfffffffd, // make the txn RBF
This allows the txn to replaced by another with higher fees. Important so that txns don't get stuck in the mempool when fees spike (as they often do).

2023-12-12 08:42 UTC, mandeeps708 requested changes

2023-12-12 08:42 UTC, mandeeps708 commented on README.md
> +docker compose up
```bash
$ docker compose 
[+] Running 1/1
 ✘ app Error                                                                                                                                                                                                                             3.7s 
Error response from daemon: pull access denied for mdip, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

@macterra I am getting this error. Am I missing something?

2023-12-12 15:35 UTC, macterra commented on README.md
> +docker compose up
Fixed docker compose to build image if missing

2023-12-12 18:02 UTC, macterra commented on lib/node/api.js
> +    // console.log('[broadcast] error', errorT);
Done

2023-12-12 22:30 UTC, mandeeps708 commented on lib/client/mdip.js
> +        // eslint-disable-next-line no-param-reassign
Sweet!

2023-12-13 21:36 UTC, mandeeps708 commented on README.md
> +docker compose up
build works perfectly now. Thank you. :star:

2023-12-13 21:38 UTC, mandeeps708 approved these changes

2023-12-13 21:44 UTC, merged